### ISSUE TITLE
Como capturar a imagem do usuário no google ?

### ISSUE THREAD

**Issue by orlandosaraivajr** [PedRufino/PI_3Semestre_BemDoCampo#20]
def _add_topbar_username_userpicture(request, context={}):
    dados_user = SocialAccount.objects.filter(user_id=request.user.id)[0]
    context['user_name'] = dados_user.extra_data.get('name')
    context['user_picture'] = dados_user.extra_data.get('picture')
    return context

**Comment by PedRufino** [comment]
Olá Orlando, Espero que esteja bem!

Conforme a ideia apresentada, realizei a captura da imagem do usuário do Google, que já está implementada no projeto.

Obrigado pela ajuda!
